version: '3.8'
services:
    mongo:
      
      image: mongo
      restart: always
      volumes:
        - mongo_data:/data/db
      ports:
        - 27017:27017
      env_file:
        - ./.env-mongo
volumes:
  mongo_data: